config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show]
  resources :posts
  resources :comments
  resources :followships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Followship', dependent: :destroy
  has_many :followed, through: :followed_users
  has_many :following_users, foreign_key: :followed_id, class_name: 'Followship', dependent: :destroy
  has_many :followers, through: :following_users
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates :first_name, length: { minimum: 1, maximum: 100, allow_blank: false }
  validates :last_name, length: { minimum: 1, maximum: 100, allow_blank: false }
  validates :email, uniqueness: true, length: { minimum: 6, maximum: 100 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.all
    @comment = Comment.new
    @comments = Comment.all
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'User not found!'
    redirect_to root_path
  end
end

app/views/users/_like_and_comment.html.haml
- posts.where(user_id: user).each do |object|
  = image_tag object.image_url if object.image_url.present?
  %h3 #{object.title}
  %h3 likes: #{ object.likes.size }
  %h3 list of users liked this post: #{ object.likes.collect { |like| like.user.email } }

  - if current_user.liked_posts.exists?(object.id)
    = button_to "Unlike", like_path(id: object.likes.find_by(user: current_user)), method: :delete, class: "btn btn-danger"
  - else
    = button_to "Like", likes_path(id: object), class: "btn btn-primary"

  = button_to 'delete post',post_path(object), method: :delete, class: "btn btn-danger" if user == current_user

  = form_with  model: @comment, local: true do |f|
    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :post_id, value: object.id
    = f.label :text, "your comment:"
    = f.text_field :text, size: 100
    = f.submit "comment", class: "btn btn-primary"


  - if comments.where(post_id: object).empty?
    %h3 There is no comments yet.
  - else
    %h3 Last comments:
    - comments.where(post_id: object).last(3).each do |comment|
      %h4 #{comment.user.full_name} : #{comment.text}

      - if comment.user == current_user || user == current_user
        = button_to 'delete comment', comment_path(comment), method: :delete, class: "btn btn-danger"

app/views/users/show.html.haml
%html
%head
%body
%h1

- if current_user_feed?
  %h2 Your feed
  = link_to "Create new post", new_post_path, class: "btn btn-primary"
- elsif followed_user_feed?
  %h2  #{@user.full_name},s feed
  = button_to "Unfollow", followship_path(id: Followship.find_by(followed_id: @user, follower_id: current_user )), method: :delete, class: "btn btn-danger"
- else
  %h2 #{@user.full_name}
  %h3 If you want to see my feed, please follow me!
  = button_to "Follow", followships_path(id: @user.id), class: "btn btn-primary"

= render partial: 'like_and_comment', locals: {user: @user, posts: @posts, comments: @comments } if current_user_feed? || followed_user_feed?