config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show]
  resources :posts
  resources :comments
  resources :followships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
end

app/views/layouts/_footer.html.haml
%footer.footer.mt-auto.py-3.bg-light
  .container
    %span.text-muted Alexey Leskov 2022

app/views/layouts/_header.html.haml
%body
  %header.p-3.bg-dark.text-white
    .container
      = link_to "Instagram", root_path, id: "logo"
      .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
        %a.d-flex.align-items-center.mb-2.mb-lg-0.text-white.text-decoration-none{:href => "/"}
          %svg.bi.me-2{:height => "32", :width => "40"}
            %use{"xlink:href" => "#bootstrap"}
        %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        .text-end
        - if current_user
          = link_to "#{current_user.email}", user_path(current_user)
          = button_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger'
        - else
          = link_to "Login", new_user_session_path, class: 'btn btn-warning'
          = link_to "Sign-up", new_user_registration_path, class: 'btn btn-warning'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Instagram
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css", :integrity => "sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")

      = yield
      = render 'layouts/footer'